import pytest
import pandas as pd
import io
import sys
from unittest.mock import patch, MagicMock

def test_column_pruning():
    # Mock streamlit cache to avoid hashing issues with BytesIO in test environment
    mock_cache = lambda func=None, **kwargs: func if func else (lambda f: f)

    with patch('streamlit.cache_resource', mock_cache):
        # Re-import to apply the mock decorator
        if 'src.io.ingestion' in sys.modules:
            del sys.modules['src.io.ingestion']
        from src.io.ingestion import load_panel_data

        # Create a dummy dataframe with extra columns
        df = pd.DataFrame({
            'DEFECT_TYPE': ['Nick'],
            'UNIT_INDEX_X': [1],
            'UNIT_INDEX_Y': [1],
            'Verification': ['Real'],
            'EXTRA_COL_1': ['Should be removed'],
            'EXTRA_COL_2': [123],
            'X_COORDINATES': [1000],
            'Y_COORDINATES': [2000]
        })

        # Save to Excel in memory
        buffer = io.BytesIO()
        with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
            df.to_excel(writer, sheet_name='Defects', index=False)
        buffer.seek(0)

        # Monkey patch name so load_panel_data can regex it
        buffer.name = "BU-01F.xlsx"

        # Run ingestion
        try:
            # Wrap in list as expected by function
            panel_data = load_panel_data([buffer], 7, 7, 470, 470, 3.0, 3.0)

            layer = panel_data.get_layer(1, 'F')

            # If layer is None, it means loading failed.
            if layer is None:
                 pytest.fail("Layer 1F not loaded. Check pandas engine compatibility.")

            data = layer.data
            columns = data.columns.tolist()

            # Check pruning
            assert 'EXTRA_COL_1' not in columns, "EXTRA_COL_1 should be pruned"
            assert 'EXTRA_COL_2' not in columns, "EXTRA_COL_2 should be pruned"
            assert 'DEFECT_TYPE' in columns
            assert 'UNIT_INDEX_X' in columns
            assert 'Verification' in columns
            assert 'X_COORDINATES' in columns

            # Verify that required downstream columns are present (either preserved or generated)
            assert 'QUADRANT' in columns, "QUADRANT must be present (generated by BuildUpLayer)"

        except ImportError:
            pytest.skip("Calamine or dependencies missing")
        except Exception as e:
            pytest.fail(f"Ingestion failed: {e}")
